name: Laravel NSTP

# define when the action should run
on:
  push:
    branches: [ "main" ]

# define the jobs
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: none
    - uses: actions/checkout@v4
    - name: Copy .env
      run: cp .env.example .env
    - name: Install or update composer
      run: composer update
    - name: Optimize Laravel Artisan
      run: php artisan optimize:clear
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test
