name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, sqlite, tokenizer, xml, zip
    - uses: actions/checkout@v4
    - name: Copy .env
      run: cp .env.example .env
    - name: Install or update composer
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
    - name: Cache Laravel Artisan
      run: php artisan cache:clear
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: php artisan test
